experiment: default_test
data:
  seed: 42
  train_fraction: 0.8
  list:
    - data/supervisely/zbirnyk/tom_1/1108-2162-1-PB
    - data/supervisely/zbirnyk/tom_1/1120-2163-1-PB
    - data/supervisely/zbirnyk/tom_1/1131-2195-1-PB
train:
  epochs: 10000
  lr: 0.0001
  batch: 16
val:
  batch: 5
model:
  name: torch-unet
  params:
    in_channels: 1
    pretrained: False
